spring.application.name=SpringIdentityCore
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true